name = "optisign-photo-slideshow"
compatibility_date = "2024-01-01"

# Required field for Cloudflare Pages
pages_build_output_dir = "public"

# Pages Functions environment variables
[vars]
QUEUE_CAP = "20"
UA_CHECK_ENABLED = "false"

# Pages Functions bindings
[[r2_buckets]]
binding = "PHOTO_BUCKET"
bucket_name = "optisign-photos"

[[kv_namespaces]]
binding = "PHOTO_QUEUE"
id = "5fe15ae5af61471cb4201f81b6998c06"
preview_id = "5fe15ae5af61471cb4201f81b6998c06"

[[kv_namespaces]]
binding = "PHOTO_DEFAULT_META"
id = "a096b3824ccc4684a5647e530e0208dc"
preview_id = "a096b3824ccc4684a5647e530e0208dc"

# Note: Scheduled triggers and Images API bindings are not supported in Pages Functions
# These features will need to be implemented differently or moved to a separate Worker

# Secrets (set via wrangler pages secret put)
# UNLISTED_SLUG: a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8a9b0c1d2e3f4g5h6i7j8
# ADMIN_TOKEN - password for reset endpoint (choose a secure password)
# CLOUDFLARE_ACCOUNT_ID: b6769d00043f804fb28cb0f092ca8d92
# CLOUDFLARE_API_TOKEN - API token with appropriate permissions
# CLOUDFLARE_ACCOUNT_HASH - for image delivery (if using Images API)
